### ISSUE TITLE
UDP Service Attacker Detection Not Working

### ISSUE THREAD

**Issue by Xewdy444** [tbiens/icarus#8]
The script doesn't seem to pick up attacking IPs when a UDP packet is sent to a UDP honeypot port such as one of the default UDP ports, 161.

**Comment by tbiens** [comment]
Hello,

Really good catch, thanks so much for reporting! The port opens but apparently in python 3.7 they changed how async udp server is coded and broke things. My code was python 3.6 style. 

Looking at the newer versions of the same module:

Deprecated since version 3.8, will be removed in version 3.10: The loop parameter.

It would seem this is still unstable in future versions and syntax will be changing again in the future.

I suspect I should drop async support and go to socketserver which I use for TCP side. 

Looks like I have a working solution. Just going to let it run for a little bit to ensure it's stable.

**Comment by tbiens** [comment]
Hello,

It ran fine overnight. I pushed the fix out to Stable. Can you give it a try please?

**Comment by Xewdy444** [comment]
Yes, I can test it out.

**Comment by Xewdy444** [comment]
Works great now. Thank you for fixing this.

**Comment by tbiens** [comment]
Thanks so much for your time in helping!
